services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
  bot:
    build: ./bot 
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped
  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - VIRTUAL_HOST=paranoia.bulattim.ru
      - VIRTUAL_PORT=80
    restart: unless-stopped


volumes:
  db-data:
