services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
  bot:
    build: ./bot 
    env_file: .env


volumes:
  db-data:
