services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
  bot:
    build: ./bot 
    env_file: .env
    depends_on:
      - db
  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db


volumes:
  db-data:
